### ISSUE TITLE
External Modules Calls Without Imports Causing Errors On basic.py

### ISSUE THREAD

**Issue by DEMON1A** [R37r0-Gh057/Malicious_Page_Builder#1]
- In `core/basic.py` you're using both modules `ctypes` - Line *39* and `sleep` - Line *41* without importing them into the basic script. that causes some errors. just fix this by importing them at the top of the file.

```python
import ctypes
from time import sleep
```

- Error dump from `error.txt`:

```
2021_02_07-23_50_16 : name 'ctypes' is not defined

2021_02_07-23_54_38 : name 'sleep' is not defined
```

- Faced these issues while running the program on python 3.7.4 - window 10 LOL.

**Comment by R37r0-Gh057** [comment]
you're collaborator, you should have fixed it without creating this issue lol
